### ISSUE TITLE
dev-libs/libusb-compat missing lib32 USE-Flag

### ISSUE THREAD

**Issue by heiko** [sjnewbury/multilib-overlay#2]
virtual/libusb seems to need lib32 Use-Flag in dev-libs/libusb-compat and dev-libs/libusb. 
Unfortunately there is no dev-libs/libusb-compat ebuild in your overlay. 

Solved: You don't need the compat ebuild. Sorry

**Comment by sjnewbury** [comment]
Not an issue then? Closing...
