### ISSUE TITLE
net-print/cups has the wrong size its its Manifest

### ISSUE THREAD

**Issue by jporterf** [sjnewbury/multilib-overlay#3]
Getting an error as follows when compiling cups from the multilib overlay:

> > > Emerging (1 of 248) net-print/cups-1.3.11-r1 from multilib
> > > Downloading 'http://gentoo.osuosl.org/distfiles/cups-1.3.11-source.tar.bz2'
> > > --2009-12-07 15:54:00--  http://gentoo.osuosl.org/distfiles/cups-1.3.11-source.tar.bz2
> > > Resolving gentoo.osuosl.org... 64.50.236.52
> > > Connecting to gentoo.osuosl.org|64.50.236.52|:80... connected.
> > > HTTP request sent, awaiting response... 200 OK
> > > Length: 3799393 (3.6M) [application/x-tar]
> > > Saving to: `/usr/portage/distfiles/cups-1.3.11-source.tar.bz2'

100%[======================================>] 3,799,393    657K/s   in 5.7s    

2009-12-07 15:54:06 (649 KB/s) - `/usr/portage/distfiles/cups-1.3.11-source.tar.bz2' saved [3799393/3799393]

('Filesize does not match recorded size', 3799393, 3799424)
!!! Fetched file: cups-1.3.11-source.tar.bz2 VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      3799393
!!! Expected: 3799424
Refetching... File renamed to '/usr/portage/distfiles/cups-1.3.11-source.tar.bz2._checksum_failure_.mPb1_h'

.
.
.
several retries later
- Fetch failed for 'net-print/cups-1.3.11-r1', Log file:
-  '/var/tmp/portage/net-print/cups-1.3.11-r1/temp/build.log'

> > > Failed to emerge net-print/cups-1.3.11-r1, Log file:
> > > 
> > >  '/var/tmp/portage/net-print/cups-1.3.11-r1/temp/build.log'
- Messages for package net-print/cups-1.3.11-r1:
- Fetch failed for 'net-print/cups-1.3.11-r1', Log file:
-  '/var/tmp/portage/net-print/cups-1.3.11-r1/temp/build.log'

**Comment by sjnewbury** [comment]
Should be fixed now.
