### ISSUE TITLE
Unable to compile net-fs/samba from overlay

### ISSUE THREAD

**Issue by jporterf** [sjnewbury/multilib-overlay#4]
When I attempt to compile the application I get after the configure stage:

> > > Source configured.
> > > Compiling source in /var/tmp/portage/net-fs/samba-3.0.37/work/samba-3.0.37 ...
> > > make -j2 -j1 proto 
> > > make: **\* No rule to make target `proto'.  Stop.

**Comment by Vlooe** [comment]
issue still valid?

**Comment by jporterf** [comment]
fixed

**Comment by Vlooe** [comment]
closed
