### ISSUE TITLE
Need new Manifest for sys-libs/libsmbios

### ISSUE THREAD

**Issue by adamphunt** [sjnewbury/multilib-overlay#5]
Can you generate a new Manifest file for sys-libs/libsmbios?  Thanks.

> > > Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /usr/local/portage/layman/multilib/sys-libs/libsmbios/files/libsmbios-2.0.3-gcc44.patch

**Comment by Vlooe** [comment]
fixed some time ago
