### ISSUE TITLE
media-libs/imlib2 not running configure

### ISSUE THREAD

**Issue by mannahusum** [sjnewbury/multilib-overlay#6]
media-libs/imlib2 didn't call econf, and so wouldn't build for me.

I added a line in multilib-native_src_configure_internal to make it work, but I guess that's not the solution:
    export MY_ECONF="
        $(use_with X x) \
        $(use_with jpeg) \
        $(use_with png) \
        $(use_with tiff) \
        $(use_with gif) \
        $(use_with zlib) \
        $(use_with bzip2) \
        $(use_with mp3 id3) \
        ${myconf} \
    "

```
enlightenment_src_configure
```

}

**Comment by Vlooe** [comment]
fixed
